### PR TITLE
introduce serial pk on default values

### PR DESCRIPTION
**Pull request by cymed**
solves #341

### CODE REVIEW

**Comment by sjib** [comment]
20240726_form_default_values_corrected_table

Table now works with second and third value

**Comment by sjib** [comment]
@cymed With you're new patch applied I get now the following error: `CRITICAL    Error : Could not check database validity: name 'item' is not defined`

20240801_validity_check_on_startup
20240801_validity_check_tww_od default_values
20240801_validity_check

I hope I did all well.

Maybe still something to adapt here?

    @staticmethod
    def get_validity_check_issues() -> List[str]:
        messages = []
        messages = DatabaseUtils.check_oid_prefix()
        messages.extend(DatabaseUtils.check_fk_defaults())

        if not DatabaseUtils.check_symbology_triggers_enabled():
            messages.append("Symbology triggers are disabled")

        return messages

Else I have to make another test on a new clean version.

**Comment by cymed** [comment]
Should work after renaming the iterator

**Comment by sjib** [comment]
When applying the new datamodel/changelogs/0001/14_default_values.sql without fk_dataprovider it works for me.
thanks @cymed

**Review by sjib — APPROVED** [review]
Looks ok from my side.

**Pull request merged**
