### PR TITLE
2024-08-28-patch-documentation

### PR DESCRIPTION
**Pull request by sjib**
grafik

- [x] Filepathes are not correct - rename image name to fit path
- [ ] Table does not display correctly
grafik

### CODE REVIEW

**Comment by sjib** [comment]
@ponceta Any way to check if table displays correctly?

**Comment by ponceta** [comment]
```
.. list-table:: STEPS
   :widths: 33 33 3
   :header-rows: 1

  * - Export step
    - Description
    - Log File 
  * - Export schema
    - ...
```

**Comment by sjib** [comment]
Thanks, I was using markdown syntax - https://markdown-syntax.de/Was-ist-Markdown/

**Comment by sjib** [comment]
@ponceta Now it should be ok

**Review by ponceta — APPROVED** [review]

**Pull request merged**
