### PR TITLE
2024-08-07-unique-constraint-fk_1-fk_2-to-re_-tables

### PR DESCRIPTION
**Pull request by sjib**
Should solve https://github.com/teksi/wastewater/issues/365

### CODE REVIEW

**Comment by ponceta** [comment]
fk_building_group is not yet created, it has to be created before this additionnal statement otherwise it will fail as it is. (see docker logs in create dumps action to see the error)

https://github.com/teksi/wastewater/blob/f13c17a9919418ab49531d2bd97b5742fddf9cb1/datamodel/changelogs/0001/03_tww_db_dss.sql#L2966C58-L2966C76

**Comment by sjib** [comment]
Needs https://github.com/teksi/wastewater/pull/357 to be user friendly, else we will get a problem during import as duplicates will be blocked. This would be ok as long as we re-import the same re_table data, but makes it difficult if there are some new ones and some old one.

**Comment by sjib** [comment]
@ponceta l moved unique constraints to the end - now it looks ok

**Comment by sjib** [comment]
@cymed also ok for you?

**Review by cymed — APPROVED** [review]

**Review by domi4484 — APPROVED** [review]
Looks good to me

**Review by ponceta — APPROVED** [review]

**Pull request merged**
