### PR TITLE
2024-04-22-patch-datatypes_postgres

### PR DESCRIPTION
**Pull request by sjib**
- [x] Adapt datatypes to fit INTERLIS definitions - should solve https://github.com/teksi/wastewater/issues/213
- [x] Improve sort order in *dictionaries - classid, attributeid, valueid - else if a new attribute or value is added the list is randomly extended.

### CODE REVIEW

**Comment by sjib** [comment]
- [ ] Harmonization of translation for Attributes Art in English: kind instead of type (use only for subclass differentiation in TEKSI e.g. for wastewater_structure)

**Comment by sjib** [comment]
Avoids conflicts with `TYPE` statements - reserved key word: https://www.postgresql.org/docs/current/sql-keywords-appendix.html

**Review by cymed — APPROVED** [review]

**Comment by ponceta** [comment]
Is this ready?

**Comment by sjib** [comment]
@ponceta Yes you can merge it - thanks!

**Pull request merged**
