### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by ponceta**
Updated project for TESKI Wastewater

Follow https://github.com/teksi/wastewater/discussions/22 for updates

Work from @urskaufmann

### CODE REVIEW

**Comment by sjib** [comment]
When I want to open the pipe_profile table, I get the follwoing error:
20231129_od_pipe_profile_error
`2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_28 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_28 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_29 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_29 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_30 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_30 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_31 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_31 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_33 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_33 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_34 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_34 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_36 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_36 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_37 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_37 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_40 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_40 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen
2023-11-29T11:21:39     WARNING    Query: BEGIN READ ONLY;DECLARE qgis_41 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048) returned 7 [FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             ]
2023-11-29T11:21:39     WARNING    1 cursor states lost.
             SQL: BEGIN READ ONLY;DECLARE qgis_41 BINARY CURSOR FOR SELECT "obj_id"::text,"status"::text,"identifier"::text FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
             Result: 7 (FEHLER: Syntaxfehler bei »9048«
             LINE 1: ...xt FROM "tww_od"."organisation" WHERE ("status" IS NOT 9048)
              ^
             )
2023-11-29T11:21:39     WARNING    NOTICE: WARNUNG: keine Transaktion offen`

**Comment by sjib** [comment]
I have created a small test data set for organisations with one organisation that has status 'gone' (9048):
20231127_organisation_testdataset

[insert_testdata_tww_organisation.zip](https://github.com/teksi/wastewater/files/13499266/insert_testdata_tww_organisation.zip)

Maybe this helps to debug.

**Comment by sjib** [comment]
And some testdata for pipe_profile
[insert_testdata_tww_pipe_profile.zip](https://github.com/teksi/wastewater/files/13499450/insert_testdata_tww_pipe_profile.zip)

**Review by sjib — CHANGES_REQUESTED** [review]
See error reports above

**Comment by ponceta** [comment]
Same issue here, probably due to the fact that there are no entities in organisation.

In the organisation layer we have blank relations which have to be cleared.

image

**Comment by urskaufmann** [comment]
I can not reproduce your error. I have organization- and pipe_profile-records from Aletsch-Musterdatensatz imported (with BAT-File). I have no error-message.

**Comment by urskaufmann** [comment]
Also this "status is not 9048" works. If I set an organisation to "gone", then it's no more in the list of the organisations ...

**Comment by ponceta** [comment]
CI fails? has anyone updated the .qgs project inbetween?

**Comment by 3nids** [comment]
yes updated here: https://github.com/teksi/wastewater/commit/cf45b349c4c034adf7f72ba6248e142c47d80dd5

**Comment by 3nids** [comment]
superseded by #67

**Pull request closed without merging**
