### PR TITLE
set obj_id sequences when importing

### PR DESCRIPTION
**Pull request by cymed**
This PR sets the sequences used for obj_id generation based on the current value of the sequence and the highest imported postfix with a matching shortcut. Mainly necessary when importing a dataset that was exported by TEKSI. Tackles #117

### CODE REVIEW

**Comment by sjib** [comment]
@cymed Funktioniert das auch wenn du Daten mit verschiedenen Präfixes hast in einer Tabelle?

**Comment by urskaufmann** [comment]
I do not really understand the code. I think to understand, that the prefix has no effect !?
I think that is not efficient. The postfix has to be unique per prefix and not overall.
If I choose a new prefix (what reason ever - because there are to many records), I should have a function who resets the sequence numbers. If I have to migrate my old database (that has three prefixes, two from the merged communities and one for the cantons road_drainage), I want the sequence_number for new records to be dependent on the actual prefix.

**Comment by cymed** [comment]
> I do not really understand the code. I think to understand, that the prefix has no effect !? I think that is not efficient. The postfix has to be unique per prefix and not overall. If I choose a new prefix (what reason ever - because there are to many records), I should have a function who resets the sequence numbers. If I have to migrate my old database (that has three prefixes, two from the merged communities and one for the cantons road_drainage), I want the sequence_number for new records to be dependent on the actual prefix.

The latest push includes the oid_prefix and re-sets all sequences to the new prefix once there is change in tww_sys.oid_prefixes, making it more dynamic.

**Comment by ponceta** [comment]
Same question as @sjib, what happens when you import data with a different oid than the active one?

**Comment by sjib** [comment]
- [ ] I think it is right that the obj_id sequence is reset with taking into account the active prefix - because new data will be created using that prefix.

- [ ] If you change the prefix - then the obj_Id sequence again is adapted - and you can continue to create data with that new prefix.

So whether we import data with different prefixes or not seems not relevant here. More relevant is that it is clear with which prefix the user wants to go on creating new data.

- [ ] Updating obj_id sequence after each import I think is a good thing to implement - then we are sure that if any new data with the chosen prefix is added the obj_id sequence is adjusted before going on with adding data (original need from Urs in #117)

- [ ] So maybe we should include this fonctionality also on to a a new button or have some visualisation what prefix is currently acitve - see https://github.com/teksi/wastewater/pull/319

@cymed @urskaufmann @ponceta - are we here all at the same point of understanding?

**Comment by cymed** [comment]
> * [ ]  I think it is right that the obj_id sequence is reset with taking into account the active prefix - because new data will be created using that prefix.
> 
>     * [ ]  If you change the prefix - then the obj_Id sequence again is adapted - and you can continue to create data with that new prefix.
> 
> 
> So whether we import data with different prefixes or not seems not relevant here. More relevant is that it is clear with which prefix the user wants to go on creating new data.
> 
>     * [ ]  Updating obj_id sequence after each import I think is a good thing to implement - then we are sure that if any new data with the chosen prefix is added the obj_id sequence is adjusted before going on with adding data (original need from Urs in [Sequence number not correct after import #117](https://github.com/teksi/wastewater/issues/117))
> 
>     * [ ]  So maybe we should include this fonctionality also on to a a new button or have some visualisation what prefix is currently acitve - see [Ensure that triggers stay active in case of error #319](https://github.com/teksi/wastewater/pull/319)
> 
> 
> @cymed @urskaufmann @ponceta - are we here all at the same point of understanding?

I agree in general. If we want to show which prefix is active, Also, once we go towards multitenancy, we'll need a way to switch between tenants anyway

**Comment by urskaufmann** [comment]
I agree with @sjib . And to show the active prefix is also good idea (anyway,  if you care, you will see the active prefix with every new record you create in the obj_id...)

**Comment by cymed** [comment]
@cymed dependecies on merging #381

**Review by sjib — COMMENTED** [review]
Would it be wise to add some tests for that also?

**Comment by cymed** [comment]
> Would it be wise to add some tests for that also?

What could break it? I don't have the time for creating the tests...

**Review by ponceta — APPROVED** [review]

**Pull request merged**
