### PR TITLE
Add sslmode to QGIS .qgs project

### PR DESCRIPTION
**Pull request by ponceta**
Add sslmode to QGIS .qgs project

- [x] sslmode=prefer as default parameter

### CODE REVIEW

**Comment by urskaufmann** [comment]
I have always used ssl mode = prefer, when adding layers to the project. But in the project was no ssl entry. Why?

**Comment by ponceta** [comment]
> I have always used ssl mode = prefer, when adding layers to the project. But in the project was no ssl entry. Why?

Probably because we use a pg_conf that can handle it directly? No clear idea why exactly, and not sure if enforcing it in the qgs file is a good idea or not. This was mainly harmonization work between TWW and TDH.

**Comment by cymed** [comment]
I am in favour of leaving it empty. See also https://github.com/qgis/QGIS/issues/58936

**Comment by cymed** [comment]
Also it is smart imho to only have on open pr altering the qgs project. It is easy to overwrite changes otherwise

**Comment by ponceta** [comment]
As discussed in upstream QGIS issue, it makes no sense to add sslmode to a pg_service configured QGIS project.

This has to be taken into account on TDH project as well.

**Pull request closed without merging**
