### PR TITLE
add error message to twwnetwork

### LINKED ISSUE #456: UnboundLocalError: cannot access local variable 'vertex' where it is not associated with a value
**Describe the bug**

Run refresh network topology (on opening project or manually)

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

```
2024-10-12T20:21:10     CRITICAL    Error : Status 7 (FEHLER: storniere Anfrage wegen Zeitüberschreitung der Anfrage
             CONTEXT: SQL-Anweisung »REFRESH MATERIALIZED VIEW tww_app.vw_network_node«
             PL/pgSQL-Funktion tww_app.network_refresh_network_simple() Zeile 106 bei SQL-Anweisung
             )
2024-10-12T20:21:10     WARNING    Python-Fehler : Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).
```
```
2024-10-12T20:16:21     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 446, in onLayersAvailable
              self.network_analyzer.setNodeLayer(layers["vw_network_node"])
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 94, in setNodeLayer
              self.createGraph()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 219, in createGraph
              self._addVertices()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 116, in _addVertices
              self.graph.add_node(fid, point=vertex, objType=obj_type, objId=obj_id)
              ^^^^^^
             UnboundLocalError: cannot access local variable 'vertex' where it is not associated with a value
```

**Desktop (please complete the following information):**
 - TWW version 2024.0.2
 - QGIS Version 3.34.8
 - OS Windows 10

**Additional context**

Very big dataset - do we have a timeout somewhere in the code?

### PR DESCRIPTION
**Pull request by cymed**
fix #456

### CODE REVIEW

**Comment by sjib** [comment]
@cymed Adding message is a great first step, but I still get the error
```

2024-10-14T17:33:05     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 446, in onLayersAvailable
              self.network_analyzer.setNodeLayer(layers["vw_network_node"])
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 96, in setNodeLayer
              self.createGraph()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 220, in createGraph
              self._addVertices()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_2024.0.2/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 117, in _addVertices
              self.graph.add_node(fid, point=vertex, objType=obj_type, objId=obj_id)
              ^^^^^^
             UnboundLocalError: cannot access local variable 'vertex' where it is not associated with a value
```

I think we would have to set a default / replacement value for vertex.
What would make sense to add? 
Can we add NULL? Or 0?

**Comment by sjib** [comment]
Here some hints how to create a QGIS point:
https://gis.stackexchange.com/questions/380783/extracting-x-y-coordinates-from-qgsgeometry-pointx-y-using-pyqgis

**Comment by sjib** [comment]
@cymed I added:
```

            except ValueError:
                # self.logger.error(f"No Geometry found for Node {obj_id} (Type: {obj_type})")
                self.logger.error(f"No Geometry found for Node {obj_id} (Type: {obj_type}) - set to default value!")
                geom = QgsGeometry.fromPointXY(QgsPointXY(58746.43000004297, -256665.088999123))
                vertex = geom.asPoint() # QgsPointXY

            self.graph.add_node(fid, point=vertex, objType=obj_type, objId=obj_id)

            self.vertexIds[str(obj_id)] = fid

        self._profile("add vertices")
```

This seems to work - and now network following works also:
grafik

What do you think?

**Comment by cymed** [comment]
fallback to main cover xy?

**Comment by urskaufmann** [comment]
Perhaps I do not get the problem...  If there are missing geometry in reach points, the fallback is the wastewater node (from fk_wastewater_networkelement) and then in a second step the cover. 
This example is from network_layers? Import is done, but REFRESH MATERIALIZED VIEW fails? I'm not sure, if we should give then an "automatic" solution for missing data.

If seen last week an XTF-File with following error from ilivalidator: Haltung_nachHaltungspunktAssocRef should associate 0 to 1 target objects (instead of 2). Obviously there where not 2 reachpoints for each reach...  : Es gibt nichts, das es nicht gibt!

**Comment by sjib** [comment]
Main cover geometry is also missing in this dataset

**Comment by sjib** [comment]
My main point is to have a user friendly feedback that gives clear description of the problem. So maybe we have to review the process and see where we can create an error log and a final message(s) about the problems
- no reach_point geometry
- no wastewater_node geometry
- no main cover geometry

So if I understand right the code should only fail if all 3 are missing?
Would it be helpful to add error log entries with the other two cases, to give helpful user feedback for improving the data?

**Comment by urskaufmann** [comment]
if there is a reachpoint, a wastewater node, a cover, they should have also x and y. Only cover has Lagegenauigkeit. Fallback to reach point xy is for me a nogo (normally there are several reachpoints with a node, they could have different xy, you would have to test...).

**Comment by cymed** [comment]
> @cymed I added:
> 
> ```
> 
>             except ValueError:
>                 # self.logger.error(f"No Geometry found for Node {obj_id} (Type: {obj_type})")
>                 self.logger.error(f"No Geometry found for Node {obj_id} (Type: {obj_type}) - set to default value!")
>                 geom = QgsGeometry.fromPointXY(QgsPointXY(58746.43000004297, -256665.088999123))
>                 vertex = geom.asPoint() # QgsPointXY
> 
>             self.graph.add_node(fid, point=vertex, objType=obj_type, objId=obj_id)
> 
>             self.vertexIds[str(obj_id)] = fid
> 
>         self._profile("add vertices")
> ```
> 
> This seems to work - and now network following works also: grafik
> 
> What do you think?

Do we need a fallback? if we have wastewater nodes without a geometry we will eventually run into problems no matter what

**Comment by sjib** [comment]
Great - no more crash anymore. And an error message. 

grafik

Discuss with @teksi/technical-group if this is enough or where else to display that error message!

**Comment by sjib** [comment]
Not tested yet with wastewater_node and reach_point

**Comment by sjib** [comment]
If we have no reach_point and no wastewater geometry we still get:
```
2024-10-31T13:06:55     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 112, in _addVertices
              vertex = feat.geometry().asPoint()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
             ValueError: Null geometry cannot be converted to a point.
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 456, in onLayersAvailable
              self.network_analyzer.setNodeLayer(layers["vw_network_node"])
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 94, in setNodeLayer
              self.createGraph()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 220, in createGraph
              self._addVertices()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 115, in _addVertices
              raise ValueError(f"No Point Geometry found for Node {obj_id} (Type: {obj_type})")
             ValueError: No Point Geometry found for Node ch2035rdKeY8avwU (Type: reach_point)
```

**Comment by cymed** [comment]
> If we have no reach_point and no wastewater geometry we still get:
> ```
> 2024-10-31T13:06:55     WARNING    Traceback (most recent call last):
>               File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 112, in _addVertices
>               vertex = feat.geometry().asPoint()
>               ^^^^^^^^^^^^^^^^^^^^^^^^^
>              ValueError: Null geometry cannot be converted to a point.
>              
>              During handling of the above exception, another exception occurred:
>              
>              Traceback (most recent call last):
>               File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 456, in onLayersAvailable
>               self.network_analyzer.setNodeLayer(layers["vw_network_node"])
>               File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 94, in setNodeLayer
>               self.createGraph()
>               File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 220, in createGraph
>               self._addVertices()
>               File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 115, in _addVertices
>               raise ValueError(f"No Point Geometry found for Node {obj_id} (Type: {obj_type})")
>              ValueError: No Point Geometry found for Node ch2035rdKeY8avwU (Type: reach_point)
> ```
> 

... so my fix works, we get an error message we can debug

**Comment by sjib** [comment]
@ponceta @cymed Ok, for me ready to merge

**Review by ponceta — APPROVED** [review]

**Pull request merged**
