### PR TITLE
Add .qgs project for TWW

### PR DESCRIPTION
**Pull request by ponceta**
New .qgs project for TEKSI Wastewater

**Goal** : Once this is finished, the fine configuration of attributes widgets and informations can be set up.

- [x] Add previous .qgs project
- [x] Rename project
- [x] Rename pg_configuration
- [x] Rename schemas
- [x] Rename layers
- [x] Replace qgep mentions
- [x] List text replacement queries to ease customer project migrations (2024)

Progress : DRAFT in progress

**Search and replace:**

On linux : 

`sed -i "s/oldValue/newValue/g" file.txt`

```
PG Service, pg_qgep, pg_tww
Views to app, qgep_od&quot;.&quot;vw, tww_app&quot;.&quot;vw
Views to app, "qgep_od"."vw, "tww_app"."vw
Schema od, qgep_od, tww_od
Schema vl, qgep_vl, tww_vl
Rename qgep views, vw_qgep, vw_tww
QGEP Prefixes, qgep_cover_prefix, tww_cover_prefix
QGEP Prefixes, qgep_bottom_prefix, tww_bottom_prefix
QGEP Prefixes, qgep_input_prefix, tww_input_prefix
QGEP Prefixes, qgep_output_prefix, tww_output_prefix
Geometries, situation_geometry, situation3d_geometry
Geometries, progression_geometry, progression3d_geometry
Geometries, detail_geometry_geometry, detail_geometry3d_geometry
Network geometries are 2D, "tww_app"."vw_network_node" (situation3d_geometry), "tww_app"."vw_network_node" (situation_geometry)
Network geometries are 2D, &quot;tww_app&quot;.&quot;vw_network_node&quot; (progression3d_geometry), &quot;tww_app&quot;.&quot;vw_network_node&quot; (progression_geometry)
Network geometries are 2D, "tww_app"."vw_network_segment" (progression3d_geometry), "tww_app"."vw_network_segment" (progression_geometry)
Network geometries are 2D, &quot;tww_app&quot;.&quot;vw_network_segment&quot; (progression3d_geometry),
&quot;tww_app&quot;.&quot;vw_network_segment&quot; (progression_geometry)
```

### CODE REVIEW

**Comment by 3nids** [comment]
can you git ignore the attachment file and remove it from the PR?

**Comment by ponceta** [comment]
Yet still remains qgep mentions of :
- qgepplugin
- wincan2qgepplugin

**Comment by 3nids** [comment]
I think we should not have any mention of these plugins here. Can you save the projet with a new profile?
(you might still need to drop these lines manually)

**Comment by ponceta** [comment]
https://github.com/teksi/wastewater/pull/8 should be merged with this.

**Pull request merged**
