### PR TITLE
2024-08-07-adapt-tww_app.vw_change_points

### PR DESCRIPTION
**Pull request by sjib**
## General
 - [x] Fix a bug

## Describe your changes
new version from urs https://github.com/teksi/wastewater/issues/59

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] CI Tests are green
- [ ] The documentation is up to date with the proposed change.
- [x] My work is ready for review

## Checklist before merge
- [x] A review has been performed
- [x] Comments are resolved
- [ ] Documentation is ready

### CODE REVIEW

**Comment by sjib** [comment]
Integrates https://github.com/teksi/wastewater/issues/59

**Comment by sjib** [comment]
@urskaufmann Please provide documentation for this new feature

- What is it intended for?
- How can you integrate it and use?

**Review by cymed — COMMENTED** [review]
We usually use wn as an alias for wastewater nodes

**Comment by sjib** [comment]
@cymed Better now?

**Review by cymed — APPROVED** [review]

**Comment by urskaufmann** [comment]
I know and it is without the split-tool not so easy to construct this case in QGEP/TWW. As I wrote in #59:
"It shows the wastewater_nodes between reaches with the same channel and with the attributes you can visualize, of the there is a change in material, in clear_height and or in slope."
also: Kanal mit mind. 2 Haltungen mit ungleichem Material/Lichte Höhe oder Gefälle und dazwischen ein Abwasserknoten (Baujahrwechsel geht nicht, da wäre es ja nicht der gleiche Kanal).

**Comment by sjib** [comment]
@urskaufmann I managed to [create a channel with two reaches](https://github.com/teksi/wastewater/discussions/374) - View change points works!
grafik

**Comment by sjib** [comment]
Change in slopes I cannot test because I cannot add a geometry to the second reach - see https://github.com/teksi/wastewater/discussions/374

**Pull request merged**
