### PR TITLE
Add subclasses of maintenance_event to project and make co_obj_id not mandatory

### PR DESCRIPTION
**Pull request by cymed**
As we can't alter the maintenance event type in vw_tww_maintenance_event and the default on creation is "unknown", we can't create maintenant events via this view. therefore, this pr adds the views of the subclasses
Also, co_obj_id and co_identifier are no longer mandatory in vw_tww_wastewater_structure because otherwise we can't edit structures without cover

### CODE REVIEW

**Comment by ponceta** [comment]
Can you please add the widget for the `fk_operating_company` to the organisation table?

image

**Review by ponceta — APPROVED** [review]
Otherwise looks good to me.

**Comment by ponceta** [comment]
@sjib what is the idea of having examination and maintenance / examination ?

image

We should encourage to create a list of people in operator and maybe linked these to their operating company.

**Comment by sjib** [comment]
> @sjib what is the idea of having examination and maintenance / examination ?

I do not really understand your question

With release 2020 we now have 3 subclasses of maintenance_event:

- maintenance
- examination
- bio_ecol_assessment

In contradiction to release 2015 it is not possible to have maintenance_event entries only - they have to be in a subclass now as maintenance_event was set to ABSTRACT in INTERLIS

grafik

I think we decided therefore to have 3 subclass views to edit the data, as they are used by different user groups and not to go with a vw_qgep_maintenance_event that includes all subclass attributes as before. 

Especially as the VSA-KEK classes extend examination with damage etc. - this would overload the whole thing.

**Comment by cymed** [comment]
The question as I understood it was: Where is the difference between the attribute "Untersuchung" in Unterhalt.Art and theUntersuchung.Erfassungsart attribute "andere"

**Comment by sjib** [comment]
These are the details for Unterhalt

```
!!@ comment = "Für Erhaltungsereignisse im Bereich Unterhalt"
CLASS Unterhalt EXTENDS Erhaltungsereignis =  
  ATTRIBUTE
    !!@ comment = "Art des Ereignisses"
    Art: (     
      andere,
      !!@ comment = "Reinigung oder Entleerung"
      Reinigung,
      !!@ comment = "Herstellung neuer Abwasserkanäle in der bisherigen oder anderer Linienführung, wobei die neuen Anlagen die Funktion der ursprünglichen Abwasserkanäle einbeziehen (SN EN 752)."
      Sanierung_Erneuerung,
      !!@ comment = "Massnahmen zur Verbesserung der aktuellen Funktionsfähigkeit von Abwasserkanälen unter vollständigem oder teilweisem Einbezug ihrerursprünglichen Substanz  (SN EN 752). In älteren Normen und Richtlinien wird diese Massnahme mit 'Sanierung' bezeichnet."
      Sanierung_Renovierung,
      !!@ comment = "Massnahmen zur Behebung örtlich begrenzter Schäden (SN EN 752). In älteren Normen und Richtlinien wird diese Massnahme mit 'Instandsetzung' bezeichnet."
      Sanierung_Reparatur,
      !!@ comment = "Alle Massnahmen zur Wiederherstellung oder Verbesserung von vorhandenen Entwässerungsanlagen. Die Massnahmen umfassen Reparatur, Renovierung und Erneuerung  (SN EN 752). In älteren Normen und Richtlinien wird dieser Begriff mit 'Erhaltung' bezeichnet."
      Sanierung_unbekannt,
      unbekannt,
      !!@ comment = "Andere Untersuchungen als TV-Untersuchungen und Biologisch Oekologische Gesamtbeurteilungen - diese mit den entsprechenden Subklassen erfassen"
      Untersuchung
    );
END Unterhalt;
```

This is only for channel TV inspections

```
!!@ comment = "Kanalfernsehuntersuchungen"
CLASS Untersuchung EXTENDS Erhaltungsereignis =  
  ATTRIBUTE
    !!@ comment = "Bezeichnung des 'bis Punktes' einer Untersuchung, so wie sie auf dem Plan erscheint. Alternative zum Fremdschlüssel Abwasserbauwerk, wenn Topologie noch nicht definiert ist (Ersterfassung). Die bisPunktBezeichnung wird später vom Hydrauliker für den Aufbau der Kanalnetztopologie verwendet. Bei Schachtuntersuchungen bleibt dieser Wert leer."
    bisPunktBezeichnung: TEXT*20;
    !!@ comment = "Aufnahmetechnik, beschreibt die Art der Aufnahme"
    Erfassungsart: MANDATORY (     
      andere,
      Begehung,
      Deformationsmessung,
      Dichtheitspruefung,
      Georadar,
      Kanalfernsehen,
      unbekannt
    );
    !!@ comment = "Eingesetztes Inspektionsfahrzeug"
    Fahrzeug: TEXT*50;
    !!@ comment = "Eingesetztes Aufnahmegeräte (Kamera)"
    Geraet: TEXT*50;
    !!@ comment = "Total untersuchte Länge in Metern mit zwei Nachkommastellen"
    Inspizierte_Laenge: MANDATORY 0.00 .. 30000.00 [m];
    !!@ comment = "Bei Videobändern steht hier die Bandnummer (z.B. 1/99). Bei elektronischen Datenträgern ist dies die Datenträgerbezeichnung (z.B. SG001). Falls pro Untersuchung eine einzelne Datei zur Verfügung steht, dann wird diese aus der Klasse Datei referenziert und dieses Attribut kann leer gelassen werden."
    Videonummer: TEXT*20;
    !!@ comment = "Bezeichnung des 'von Punktes' einer Untersuchung, so wie sie auf dem Plan erscheint. Alternative zum Fremdschlüssel Haltungspunkt, wenn Topologie noch nicht definiert ist (Ersterfassung). Die vonPunktBezeichnung wird später vom Hydrauliker für den Aufbau der Kanalnetztopologie verwendet."
    vonPunktBezeichnung: TEXT*20;
    !!@ comment = "Wetterverhältnisse während der Inspektion"
    Witterung: (     
      bedeckt_regnerisch,
      Nieselregen,
      Regen,
      Schneefall,
      schoen_trocken,
      unbekannt
    );
END Untersuchung;

```

**Pull request merged**
