### PR TITLE
Add debug points to database utils

### PR DESCRIPTION
**Pull request by cymed**
To find a solution for #505

### CODE REVIEW

**Review by ponceta — APPROVED** [review]

**Comment by ponceta** [comment]
This will be useful for any users debugging tools without any impact on production.

**Comment by sjib** [comment]
Documentation:
If you run the Validity Check you will get the information about the connection settings:
grafik

**Comment by sjib** [comment]
@cymed 
It looks like you check this two times:
`2024-12-20T16:07:10        teksi_wastewater.utils:Checking setup of default_values`

**Comment by cymed** [comment]
> @cymed 
> It looks like you check this two times:
> `2024-12-20T16:07:10        teksi_wastewater.utils:Checking setup of default_values`

Not changed in this PR

**Pull request merged**
