### PR TITLE
2024-07-20-adapt-documentation_installation

### PR DESCRIPTION
**Pull request by sjib**
## General
 - [x] Fix the documentation

### Context
Installation documentation is not up to date and leads to error in testing TWW.

## Describe your changes
- [x] Fix the installation documentation
- [x] Remove the VM obsolete approach
- [x] Mention the upcoming evolution in roles management

## Issue ticket number and link
 - [x] https://github.com/teksi/wastewater/issues/328

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] CI Tests are green
- [x] The documentation is up to date with the proposed change.
- [x] My work is ready for review

## Checklist before merge
- [x] A review has been performed
- [x] Comments are resolved
- [x] Documentation is ready

### CODE REVIEW

**Comment by sjib** [comment]
```
* Right click the `tww_prod` database

  * Click `Restore`

  * Load your download of tww_vx.y.z_structure_and_demo_data.backup
```

I suggest to call it tww_demo in this paragraph:

`* Right click the `tww_demo` database`

**Comment by sjib** [comment]
@ponceta Can we have 

- a *.backup with demodata
- and one just the structure?

Currently the CI only creates one without demodata, but it is called with demodata

**Comment by sjib** [comment]
@ponceta Adapt from dev to 2024.0

**Comment by sjib** [comment]
```
2.4.5. Install the demo project

    Download from https://github.com/TWW/tww/releases/latest the tww.zip

    Extract the file
```

The project file currently is in a zip called

**Comment by sjib** [comment]
Should solve https://github.com/teksi/wastewater/issues/328
and

- [x] Minimal requirements QGIS, networkx, postgis wrong

**Comment by sjib** [comment]
@cymed Can you review this based on your latest developments with roles?

**Comment by cymed** [comment]
My roles developments have a separate docs update. Also there are conflicts to resolve

**Review by ponceta — APPROVED** [review]

**Pull request merged**
