### PR TITLE
Enable cmd tool tests

### LINKED ISSUE #138: enable command line testing in workflow

### PR DESCRIPTION
**Pull request by domi4484**
Fix #138

### CODE REVIEW

**Comment by 3nids** [comment]
it's strange that the service is not working

**Review by 3nids — APPROVED** [review]

**Comment by domi4484** [comment]
> it's strange that the service is not working

I think the interlis tools are not able to use it

**Comment by 3nids** [comment]
let's see in #157

**Comment by domi4484** [comment]
If with service file doesn't work we should remove the --pgservice option from the cmd line tool. Or raise a not implemented error.
In model baker we had to implement something to parse the pg service and pass the right options to the ili tools. And here we don't use (that part) of MB.

**Pull request merged**
