### PR TITLE
Update QGIS project 

### PR DESCRIPTION
**Pull request by 3nids**
This is the project file from this commit fdf205fb90ee7e855a6aa1a434b08c28a180211e in PR #24 

I fixed the typo (wn_elevation_accuracy), is it expected that there were still some mentions about this despite being fixed in the datamodel? i.e. could it be that the project is not up to date with the last datamodel?

The project still contains some QGEP words in it, which is a banned keyword, this has to be fixed.

This PR supersedes #24.

### CODE REVIEW

**Comment by urskaufmann** [comment]
elevation_accuracy: I did correct this with QGIS (not with a notepad) and I can find in QGIS no more "accuray". With notepad, there are still 17 accuray. Don't no what happens, if I change this with notepad.

Similar with qgep: there is still 24x qgep in a path to a dictionary on my server and twice is qgep a part of a filename (od_file20160921105557083_object_class_obj_id_vw_wastewater_node_qgep&quot;). I can not handle this with QGIS...

project-files seems to have some legacy issues

**Comment by ponceta** [comment]
2023-12-11
https://raw.githubusercontent.com/teksi/wastewater/d03568706aa27c656d48db1eb08bb26f23cf8244/project/teksi_wastewater.qgs 

2024-01-07
https://raw.githubusercontent.com/teksi/wastewater/4733f655814d28566d427261afb96c173836918a/project/teksi_wastewater.qgs

QGEP is mentionned in both files :

```
            <editform tolerant="1">T:/12_GIS/01_QGIS/QGEP/qgep-test/tww_project_2020/forms/reach.ui</editform>
            <editforminit></editforminit>
            <editforminitcodesource>0</editforminitcodesource>
            <editforminitfilepath>T:/12_GIS/01_QGIS/QGEP/qgep-test/tww_project_2020</editforminitfilepath>
            <editforminitcode># -*- coding: utf-8 -*-
```

**Comment by 3nids** [comment]
I guess these lines could easily be dropped

**Review by ponceta — APPROVED** [review]
Great project enhancements by @urskaufmann ! Thank you a lot!

**Pull request merged**
