### PR TITLE
[WIP] Datamodel VSA-DSS 2020

### PR DESCRIPTION
**Pull request by sjib**
Development of VSA-DSS 2020 TEKSI Wastewater & GEP datamodel and scripts

### CODE REVIEW

**Comment by cymed** [comment]
> TO DO: Do we still need this? 50_maintenance_zones.sql https://github.com/teksi/wastewater/blob/fd1c5abdad14d107ef1fc904d48df4b66a00b9b8/datamodel/50_maintenance_zones.sql
> 
> Linked with SWMM export?

Linked to VSA KEK "Schachtbereich"

**Comment by sjib** [comment]
I think this is a candidate to be eliminated. Or should be renamed to be a TEKSI extension. Please comment if you still need this!

**Comment by cymed** [comment]
As long as we don't write our own VSA KEK entries for manholes, I think this can be omitted.

**Comment by sjib** [comment]
Current developments in qgep 1.6.1 to integrate:

- [x] https://github.com/QGEP/datamodel/pull/224
- [ ] https://github.com/QGEP/datamodel/pull/220
- [ ] https://github.com/QGEP/datamodel/pull/219
- [ ] https://github.com/QGEP/datamodel/pull/225
- [ ] https://github.com/QGEP/datamodel/pull/214
- [ ] https://github.com/QGEP/datamodel/pull/213 - length ok - adapt drop / create views
- [x] https://github.com/QGEP/datamodel/pull/215 - integrated in VSA-DSS 2020
- [x] https://github.com/QGEP/datamodel/pull/211 - integrated in VSA-DSS 2020

**Comment by sjib** [comment]
- [ ] Clarify if this can be done later or if it should be posted to other role?
`ALTER VIEW tww_od.vw_dictionary_field`
`  OWNER TO tww;`

@ponceta Any idea? Currently to qgep in actual qgep.

**Comment by urskaufmann** [comment]
> TO DO: Do we still need this? 50_maintenance_zones.sql https://github.com/teksi/wastewater/blob/fd1c5abdad14d107ef1fc904d48df4b66a00b9b8/datamodel/50_maintenance_zones.sql
> 
> Linked with SWMM export?

Is not VSA-DSS, so there is data loss when exporting with INTERLIS. These "Zones" or "Etappen" should be done with maintenance_events standard attributes

**Comment by sjib** [comment]
> > TO DO: Do we still need this? 50_maintenance_zones.sql https://github.com/teksi/wastewater/blob/fd1c5abdad14d107ef1fc904d48df4b66a00b9b8/datamodel/50_maintenance_zones.sql
> > Linked with SWMM export?
> 
> Is not VSA-DSS, so there is data loss when exporting with INTERLIS. These "Zones" or "Etappen" should be done with maintenance_events standard attributes

renamed to old_50_maintenance_zones.sql - can be deleted at the end of the migration process

**Comment by sjib** [comment]
`Applying post-all.py... FEHLER:  Spalte wn.backflow_level existiert nicht
LINE 152:  coalesce((wn.backflow_level-wn.bottom_level),0) as MaxDepth...`

Model adaption VSA-DSS 2020: New `backflow_level_current`

**Comment by sjib** [comment]
pum_info_set_baseline_entry.sql added

**Comment by sjib** [comment]
Still open developments from 1.6.1 to integrate see https://github.com/teksi/wastewater/pull/2#issuecomment-1747217460

@cymed Let me know when you think you finished!

I let @urskaufmann test with the current version.

**Comment by cymed** [comment]
CI checks are good.

- https://github.com/QGEP/datamodel/pull/213 is read to push
- https://github.com/QGEP/datamodel/pull/219 is working, but awaiting feedback whether labeling logic in https://github.com/QGEP/datamodel/commit/73b4fe05e90ce50c4c5e962f39031ffb41817516 is ok for all. 
- https://github.com/QGEP/datamodel/pull/220 and https://github.com/QGEP/datamodel/pull/221 have overlaps , 
- https://github.com/QGEP/datamodel/pull/224 is ready to push
- https://github.com/QGEP/datamodel/pull/225 is ready to push

**Comment by ponceta** [comment]
> Still open developments from 1.6.1 to integrate see [#2 (comment)](https://github.com/teksi/wastewater/pull/2#issuecomment-1747217460)
> 
> @cymed Let me know when you think you finished!
> 
> I let @urskaufmann test with the current version.

1.6.1 developments should a priori not interfere with VSA 2020. Bugfixes can be ported to the new version but the goal of the VSA 2020 is to port an iso functionnal version of the QGEP project (1.6.0) to TEKSI wastewater module.

If the wastewater module implementation is a success, then we can adapt the necessary evolutions brought to 1.6.1.

**Comment by 3nids** [comment]
@sjib it's a bit hard to see what you have actually done here. Would it possible that you open a pull request on the original repo (https://github.com/QGEP/datamodel) so we can have a diff available?  (we won't merge the PR in any case)

**Comment by sjib** [comment]
First commit was the baseline with the existing QGEP datamodel



https://github.com/teksi/wastewater/pull/2/commits

**Comment by 3nids** [comment]
Good thanks!

**Pull request merged**
