### PR TITLE
datamodel kek rename class.file to filename

### PR DESCRIPTION
**Pull request by sjib**
Solve conflict reserved word CLASS

### CODE REVIEW

**Comment by sjib** [comment]
@domi4484 Should solve https://github.com/teksi/wastewater/issues/133 and not make it necessary to have exception in INTERLIS import / export

**Comment by sjib** [comment]
@domi4484 But you have to rematch file.classname in your scripts - thats why tests are failing.

**Comment by ponceta** [comment]
@ponceta checks with @3nids and @domi4484 to fix matchings

**Review by 3nids — APPROVED** [review]

**Comment by ponceta** [comment]
@ponceta Error on 

`statement = 'SELECT tww_od.file.class AS tww_od_file_class, tww_od.file.obj_id AS tww_od_file_obj_id, tww_od.file.classname AS tww...er, tww_od.file.fk_data_media AS tww_od_file_fk_data_media \nFROM tww_od.file \nWHERE tww_od.file.obj_id = %(param_1)s'`

**Comment by 3nids** [comment]
@domi4484 

```python
self = <teksi_wastewater.interlis.interlis_model_mapping.model_tww_od.ModelTwwOd.__init__.<locals>.file object at 0x7fa37fbca3b0>
kwargs = {'classname_column': 3886, 'fk_data_media': 'fk11abk6w70lrfmz', 'fk_dataowner': 'ch20p3q400001497', 'fk_provider': 'ch20p3q400001497', ...}
cls_ = <class 'teksi_wastewater.interlis.interlis_model_mapping.model_tww_od.ModelTwwOd.__init__.<locals>.file'>
k = 'classname_column'
    def _declarative_constructor(self, **kwargs):
        """A simple constructor that allows initialization from kwargs.
    
        Sets attributes on the constructed instance using the names and
        values in ``kwargs``.
    
        Only keys that are present as
        attributes of the instance's class are allowed. These could be,
        for example, any mapped columns or relationships.
        """
        cls_ = type(self)
        for k in kwargs:
            if not hasattr(cls_, k):
>               raise TypeError(
                    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
                )
E               TypeError: 'classname_column' is an invalid keyword argument for file
/usr/lib/python3/dist-packages/sqlalchemy/orm/decl_base.py:1154: TypeError
```

**Pull request merged**
