### PR TITLE
Import/export wastewater structure symbols

### PR DESCRIPTION
**Pull request by cymed**
see #352

### CODE REVIEW

**Comment by sjib** [comment]
Thanks @cymed I think Abwasserbauwerk_Symbol we can support on import. 
The *_text classes do not make to import, as they will change too quickly and will be re-created by TEKSI with a next change of the data anyway.

**Comment by sjib** [comment]
```
E           AttributeError: 'abwasserbauwerk_symbol' object has no attribute 'letzte_aenderung'

teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py:2067: AttributeError
```

**Comment by sjib** [comment]
```
E               TypeError: 'symbol_scaling_height' is an invalid keyword argument for wastewater_structure_symbol

/usr/lib/python3/dist-packages/sqlalchemy/orm/decl_base.py:1197: TypeError
```

@cymed  Da scheinen wir noch einen Übersetzungs- und Schreibfehler im Modell zu haben: symbol_scaling_height statt symbol_scaling_height

Das müsste ich im create script ändern

**Comment by sjib** [comment]
> ```
> E           AttributeError: 'abwasserbauwerk_symbol' object has no attribute 'letzte_aenderung'
> 
> teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py:2067: AttributeError
> ```

@cymed I find wastewater_structure_symbol.last_modification in postgres - maybe also something I need to change. Dito for *_text. 
Can you create a new issue for that if you agree?

**Comment by cymed** [comment]
> > ```
> > E           AttributeError: 'abwasserbauwerk_symbol' object has no attribute 'letzte_aenderung'
> > 
> > teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py:2067: AttributeError
> > ```
> 
> @cymed I find wastewater_structure_symbol.last_modification in postgres - maybe also something I need to change. Dito for *_text. Can you create a new issue for that if you agree?

I agree, they both do not inherit from SIA405_BaseClass

**Review by sjib — APPROVED** [review]
@cymed looks good to me even if I cannot test right now.

Did you also adapt the export with wastewater_structure_symbol?

Else please open a new issue for that and we can do this separately.

**Comment by sjib** [comment]
@cymed Nice - thanks!
@ponceta This pull request will also influence the data model!

**Pull request merged**
